=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/3AConfig/MetadataTagIDConfigSchema.xsd
<!--
 FILE:        Metadata Tag ID Configuration Schema
 SERVICES:    Metadata Tag ID Configuration Schema
 DESCRIPTION: Defines the format for the Metadata  Tag ID Configuration XML files

Copyright (c) 2017-2020 Qualcomm Technologies, Inc.
 All Rights Reserved.
 Confidential and Proprietary - Qualcomm Technologies, Inc.
-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="HexInt">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9A-Fa-f]+|-?[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="MetadataTagIDConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TypeID" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:choice>
              <xs:element name="FieldID" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:choice>
                    <xs:element name="Enumeration" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute type="xs:string" name="Name"        use="required"/>
                        <xs:attribute type="HexInt"    name="Value"       use="required"/>
                        <xs:attribute type="xs:string" name="Description" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Bitmask" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute type="xs:string" name="Name"        use="required"/>
                        <xs:attribute type="HexInt"    name="Value"       use="required"/>
                        <xs:attribute type="xs:string" name="Description" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                  <xs:attribute type="xs:string" name="Name"        use="required"/>
                  <xs:attribute type="HexInt"    name="ID"          use="required"/>
                  <xs:attribute type="xs:string" name="Description" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Enumeration" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute type="xs:string" name="Name"        use="required"/>
                  <xs:attribute type="HexInt"    name="Value"       use="required"/>
                  <xs:attribute type="xs:string" name="Description" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Bitmask" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute type="xs:string" name="Name"        use="required"/>
                  <xs:attribute type="HexInt"    name="Value"       use="required"/>
                  <xs:attribute type="xs:string" name="Description" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:choice>
            <xs:attribute type="xs:string" name="Name"        use="required"/>
            <xs:attribute type="HexInt"    name="ID"          use="required"/>
            <xs:attribute type="xs:string" name="Description" use="optional"/>
          </xs:complexType>
          <xs:unique name="UniqueTypeFieldID">
            <xs:selector xpath="FieldID"/>
            <xs:field xpath="@ID"/>
          </xs:unique>
          <xs:unique name="UniqueTypeValue">
            <xs:selector xpath="Enumeration" />
            <xs:field xpath="@Value" />
          </xs:unique>
          <xs:unique name="UniqueTypeBitmask">
            <xs:selector xpath="Bitmask" />
            <xs:field xpath="@Value" />
          </xs:unique>
        </xs:element>
        <xs:element name="TagID" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:choice>
              <xs:element name="Enumeration" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute type="xs:string" name="Name"        use="required"/>
                  <xs:attribute type="HexInt"    name="Value"       use="required"/>
                  <xs:attribute type="xs:string" name="Description" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Bitmask" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute type="xs:string" name="Name"        use="required"/>
                  <xs:attribute type="HexInt"    name="Value"       use="required"/>
                  <xs:attribute type="xs:string" name="Description" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:choice>
            <xs:attribute type="xs:string" name="Name"        use="required"/>
            <xs:attribute type="HexInt"    name="ID"          use="required"/>
            <xs:attribute type="xs:string" name="Description" use="optional"/>
          </xs:complexType>
          <xs:unique name="UniqueTagEnum">
            <xs:selector xpath="Enumeration" />
            <xs:field xpath="@Value" />
          </xs:unique>
          <xs:unique name="UniqueTagBitmask">
            <xs:selector xpath="Bitmask" />
            <xs:field xpath="@Value" />
          </xs:unique>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="Tag" use="required"/>
      <xs:attribute type="xs:int" name="TagSize" use="required"/>
    </xs:complexType>
    <xs:unique name="UniqueTagID">
      <xs:selector xpath="TagID" />
      <xs:field xpath="@ID" />
    </xs:unique>
    <xs:unique name="UniqueTypeID">
      <xs:selector xpath="TypeID" />
      <xs:field xpath="@ID" />
    </xs:unique>
  </xs:element>
</xs:schema>

=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/3AConfig/3AMetadataTagIdConfig.xml
<?xml version = "1.0" encoding = "utf-8" ?>
<!--
 FILE:        3A Metadata Tag ID Configuration
 SERVICES:    3A Metadata Tag ID Configuration file
 DESCRIPTION: Defines the Tag ID configuration 

Copyright (c) 2017 Qualcomm Technologies, Inc.
 All Rights Reserved.
 Confidential and Proprietary - Qualcomm Technologies, Inc.
-->

<MetadataTagIDConfig Tag="Qualcomm 3A Metadata" TagSize="21" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="./ MetadataTagIDConfigSchema.xsd">
  <TypeID ID="0x41" Name="AEC ROI Dim" Description="ROI Dimensions">
    <FieldID ID="0x01" Name="Left"   Description="Unity-Normalized ROI coordinate of left of ROI"/>
    <FieldID ID="0x02" Name="Top"    Description="Unity-Normalized ROI coordinate of top of ROI"/>
    <FieldID ID="0x03" Name="Width"  Description="Unity-Normalized ROI width of ROI"/>
    <FieldID ID="0x04" Name="Height" Description="Unity-Normalized ROI width of ROI"/>
    <FieldID ID="0x05" Name="Weight" Description="ROI weight"/>
  </TypeID>
  <TypeID ID="0x42" Name="AEC Configuration"                    Description="AEC algorithm configurations and settings">
    <FieldID ID="0x01" Name="Operation Mode"                    Description="Current AEC operation mode">
      <Enumeration Value="0" Name="Init"/>
      <Enumeration Value="1" Name="Streaming"/>
      <Enumeration Value="2" Name="Preflash"/>
      <Enumeration Value="3" Name="Fast AEC"/>
      <Enumeration Value="4" Name="Aggressive AEC"/>
      <Enumeration Value="5" Name="Flash Measurement"/>
    </FieldID>
    <FieldID ID="0x02" Name="Manual AEC Mode"                   Description="Specifies the manual AEC mode">
      <Enumeration Value="0"  Name="Auto"/>
      <Enumeration Value="1"  Name="Manual ISO"/>
      <Enumeration Value="2"  Name="Manual Exp Time"/>
      <Enumeration Value="3"  Name="Manual Full"/>
    </FieldID>
    <FieldID ID="0x03" Name="Manual ISO Value"                  Description="Specifies the ISO Value under Manual ISO"/>
    <FieldID ID="0x04" Name="Manual Exposure Time"              Description="Specifies the ISO Value under Manual Exposure Time"/>
    <FieldID ID="0x05" Name="Antibanding Mode"                  Description="Specifies the Antibanding configuration">
      <Enumeration Value="0"  Name="Off"/>
      <Enumeration Value="1"  Name="50 Hz"/>
      <Enumeration Value="2"  Name="60 Hz"/>
      <Enumeration Value="3"  Name="Auto"/>
    </FieldID>
    <FieldID ID="0x06" Name="Exposure Value"                    Description="Specifies the actual EV value (converted from UI)"/>
    <FieldID ID="0x07" Name="Min FPS"                           Description="Specifies the Min FPS contraint from APP"/>
    <FieldID ID="0x08" Name="Max FPS"                           Description="Specifies the Max FPS contraint from APP"/>
    <FieldID ID="0x09" Name="Metering Mode"                     Description="Specifies the Metering Mode in use">
      <Enumeration Value="0"  Name="Center Weighted"/>
      <Enumeration Value="1"  Name="Frame Average"/>
      <Enumeration Value="2"  Name="Spot"/>
    </FieldID>
    <FieldID ID="0x0A" Name="LED Mode"                          Description="Specifies the LED mode in use">
      <Enumeration Value="0"  Name="Off"/>
      <Enumeration Value="1"  Name="Auto"/>
      <Enumeration Value="2"  Name="On"/>
    </FieldID>
    <FieldID ID="0x0B" Name="AEC Locked"                        Description="Indicates if AEC is locked"/>
    <FieldID ID="0x0C" Name="ADRC Disable Override"             Description="Indicates if ADRC Disable is Overrided"/>
    <FieldID ID="0x0D" Name="Auto White Balance Active"         Description="Indicates if Auto WhiteBalance is active"/>
    <FieldID ID="0x0E" Name="White Balance Gains"               Description="Specifies the White Balance Gains used"/>
    <FieldID ID="0x0F" Name="Gyro X"                            Description="Specifies the Gyro value in X direction"/>
    <FieldID ID="0x10" Name="Gyro Y"                            Description="Specifies the Gyro value in Y direction"/>
    <FieldID ID="0x11" Name="Gyro Z"                            Description="Specifies the Gyro value in Z direction"/>
    <FieldID ID="0x12" Name="Aperture"                          Description="Camera Module F-number"/>
    <FieldID ID="0x13" Name="Sensor Aspect Ratio"               Description="Configured stats window Aspect Ratio (W / H)"/>
    <FieldID ID="0x14" Name="Min Sensor Preview Gain"           Description="Min sensor total Gain for preview mode"/>
    <FieldID ID="0x15" Name="Max Sensor Preview Gain"           Description="Max sensor total Gain for preview mode"/>
    <FieldID ID="0x16" Name="Min Sensor Preview Exposure Time"  Description="Min sensor ExposureTime(ms) for preview mode"/>
    <FieldID ID="0x17" Name="Max Sensor Preview Exposure Time"  Description="Max sensor ExposureTime(ms) for preview mode"/>
    <FieldID ID="0x18" Name="Min Sensor Snapshot Gain"          Description="Min sensor total Gain for snapshot mode"/>
    <FieldID ID="0x19" Name="Max Sensor Snapshot Gain"          Description="Max sensor total Gain for snapshot mode"/>
    <FieldID ID="0x1A" Name="Min Sensor Snapshot Exposure Time" Description="Min sensor ExposureTime(ms) for snapshot mode"/>
    <FieldID ID="0x1B" Name="Max Sensor Snapshot Exposure Time" Description="Max sensor ExposureTime(ms) for snapshot mode"/>
    <FieldID ID="0x1C" Name="Min Total Preview Gain"            Description="Min core total Gain for preview mode"/>
    <FieldID ID="0x1D" Name="Max Total Preview Gain"            Description="Max core total Gain for preview mode"/>
    <FieldID ID="0x1E" Name="Min Total Preview Exposure Time"   Description="Min core ExposureTime(ms) for preview mode"/>
    <FieldID ID="0x1F" Name="Max Total Preview Exposure Time"   Description="Max core ExposureTime(ms) for preview mode"/>
    <FieldID ID="0x20" Name="Touch ROI Active"                  Description="Indicates if Touch ROI is active"/>
    <FieldID ID="0x21" Name="Touch ROIs"                        Description="Touch ROI information"/>
    <FieldID ID="0x22" Name="Face ROI Active"                   Description="Indicates if Touch ROI is active"/>
    <FieldID ID="0x23" Name="Face Hint Duration"                Description="Indicates face hint duration prior to status change"/>
    <FieldID ID="0x24" Name="Face Status Duration"              Description="Indicates the face status duration for the current status"/>
    <FieldID ID="0x25" Name="Valid Face ROI Count"              Description="Number of valid Face ROIs"/>
    <FieldID ID="0x26" Name="Face ROIs"                         Description="Face ROIs information"/>
  </TypeID>
  <TypeID ID="0x43" Name="AECFrameHistory" Description="AEC history of past frames">
    <FieldID ID="0x01" Name="Frame ID"                    Description="Frame ID of history entry"/>
    <FieldID ID="0x02" Name="Initial Configuration"       Description="Indicates if this entry is for the initial startup configuration"/>
    <FieldID ID="0x03" Name="Exposure Indices"            Description="Exposure indices of entry"/>
    <FieldID ID="0x04" Name="Exposure Adjustment Indices" Description="Exposure Adjustments indices of entry"/>
    <FieldID ID="0x05" Name="Exposure Target Indices"     Description="Target Exposure indices of entry"/>
    <FieldID ID="0x06" Name="Exposure Gains"              Description="Exposure Gain of entry"/>
    <FieldID ID="0x07" Name="Exposure Times"              Description="Exposure Time of entry"/>
    <FieldID ID="0x08" Name="Final Luma"                  Description="Final Metered Luma"/>
    <FieldID ID="0x09" Name="Lux Index"                   Description="Metered Lux Index"/>
    <FieldID ID="0x0A" Name="AEC Settled"                 Description="Indicates if AEC is settled in entry frame"/>
  </TypeID>
  <TypeID ID="0x44" Name="AECModeHistory" Description="AEC last operation mode information">
    <FieldID ID="0x01" Name="Valid"                 Description="Indicates validity of last mode"/>
    <FieldID ID="0x02" Name="Initial Configuration" Description="Initial frame configuration"/>
    <FieldID ID="0x03" Name="Last Frame"            Description="Last frame configuration"/>
  </TypeID>
  <TypeID ID="0x45" Name="AECMetering" Description="AEC Metering related information">
    <FieldID ID="0x01" Name="Lux Index"                      Description="Lux Index"/>
    <FieldID ID="0x02" Name="Average Luma"                   Description="Average Luma"/>
    <FieldID ID="0x03" Name="Frame Luma"                     Description="Frame Luma (with Bias)"/>
    <FieldID ID="0x04" Name="Touch ROI Luma"                 Description="Touch ROI Luma"/>
    <FieldID ID="0x05" Name="Face ROI Luma"                  Description="Face ROI Luma"/>
    <FieldID ID="0x06" Name="Min Face Luma"                  Description="Minimum Face Luma"/>
    <FieldID ID="0x07" Name="Max Face Luma"                  Description="Maximum Face Luma"/>
    <FieldID ID="0x08" Name="Face Weight"                    Description="Face Weight"/>
    <FieldID ID="0x09" Name="Final Luma"                     Description="Final Luma of Metering"/>
    <FieldID ID="0x0A" Name="Lux-based Safe Target"          Description="Reference Luma Target(Default) from Lux"/>
    <FieldID ID="0x0B" Name="Color-based Safe Target"        Description="Luma Target from Extreme Color"/>
    <FieldID ID="0x0C" Name="History-based Targets"          Description="Luma Targets from Histogram Target"/>
    <FieldID ID="0x0D" Name="Final Targets"                  Description="Final Short Luma Target"/>
    <FieldID ID="0x0E" Name="BG Stats Saturation Thresholds" Description="Saturation threshold in input BG stats"/>
  </TypeID>
  <TypeID ID="0x46" Name="AECConvergence" Description="AEC Convergence related information">
