=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/Simulator/Spectra280/DefaultConfig/XSD/meta_config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="simulationglobalelements.xsd"/>
    <xs:element name="MetaConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="module_version">
                    <xs:complexType>
                        <xs:attribute name="major_revision" type="xs:int" fixed="1"/>
                        <xs:attribute name="minor_revision" type="xs:int" fixed="0"/>
                        <xs:attribute name="incr_revision" type="xs:int" fixed="0"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CCT" type="xs:float" default="5000" />
                <xs:element name="LuxIdx" type="xs:float" default="130.0"/>
                <xs:element name="Gain" type="xs:float" default="1.0" />
                <xs:element name="shortGain" type="xs:float" default="1.0" />
                <xs:element name="digitalGain" type="xs:float" default="1.0"/>
                <xs:element name="ExpSensitivityRatio" type="xs:float" default="1.0"/>
                <xs:element name="ExpTimeRatio" type="xs:float" default="1.0"/>
                <xs:element name="ExpGainRatio" type="xs:float" default="1.0"/>
                <xs:element name="DrcGain" type="xs:float" default="1.0"/>
                <xs:element name="DrcGainDark" type="xs:float" default="1.0"/>
                <xs:element name="LensPosition" type="xs:float" default="1.0"/>
                <xs:element name="HDRMode">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:unsignedInt">
                                <xs:attribute name="range" type="xs:string" default="[0,1]"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="gain_r" type="xs:float" default="1.0"/>
                <xs:element name="gain_g" type="xs:float" default="1.0"/>
                <xs:element name="gain_b" type="xs:float" default="1.0"/>
                <xs:element name="ExpIdx" type="xs:float" default="1.0"/>
                <xs:element name="PrevExpIdx" type="xs:float" default="1.0"/>
                <xs:element name="NumOfLed" type="xs:unsignedByte" default="1"/>
                <xs:element name="Led1IdxRatio" type="xs:float" default="0.1"/>
                <xs:element name="Led2IdxRatio" type="xs:float" default="0.9"/>
                <xs:element name="HDRZrecSel" type="xs:unsignedByte" default="0"/>
                <xs:element name="HDRZrecPattern" type="xs:unsignedByte" default="0"/>
                <xs:element name="HDRZrecFirstRBExp" type="xs:unsignedByte" default="0"/>
                <xs:element name="LEDSensitivity" type="xs:float" default="1.0"/>
                <xs:element name="SensorType">
                    <xs:simpleType>
                        <xs:restriction base="xs:unsignedByte">
                            <xs:enumeration id="SENSOR_MONO" value="0"/>
                            <xs:enumeration id="SENSOR_BAYER" value="1"/>
                            <xs:enumeration id="SENSOR_PDAF" value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="aec_exp_time">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Short" type="xs:unsignedInt" />
                            <xs:element name="Safe" type="xs:unsignedInt" />
                            <xs:element name="Long" type="xs:unsignedInt" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CustomAec">
                    <xs:simpleType>
                        <xs:restriction base="floatvar">
                            <xs:length value="32"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="CustomAwb">
                    <xs:simpleType>
                        <xs:restriction base="floatvar">
                            <xs:length value="32"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="CustomAf">
                    <xs:simpleType>
                        <xs:restriction base="floatvar">
                            <xs:length value="32"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="CCM">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IFE">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Flag" type="xs:unsignedByte" />
                                        <xs:element name="Matrix">
                                            <xs:simpleType>
                                                <xs:restriction base="floatvar">
                                                    <xs:length value="9"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Offset">
                                            <xs:simpleType>
                                                <xs:restriction base="floatvar">
                                                    <xs:length value="3"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="BPS">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Flag" type="xs:unsignedByte" />
                                        <xs:element name="Matrix">
                                            <xs:simpleType>
                                                <xs:restriction base="floatvar">
                                                    <xs:length value="9"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Offset">
                                            <xs:simpleType>
                                                <xs:restriction base="floatvar">
                                                    <xs:length value="3"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="IPE">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Flag" type="xs:unsignedByte" />
                                        <xs:element name="Matrix">
                                            <xs:simpleType>
                                                <xs:restriction base="floatvar">
                                                    <xs:length value="9"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Offset">
                                            <xs:simpleType>
                                                <xs:restriction base="floatvar">
                                                    <xs:length value="3"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/Simulator/IOT280/DefaultConfig/XML/meta_config.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
========================================================================
   Copyright(c) 2018 Qualcomm Technologies, Inc.
   All Rights Reserved.
   Confidential and Proprietary - Qualcomm Technologies, Inc.
========================================================================
-->
<MetaConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\XSD\meta_config.xsd">
  <module_version major_revision="1" minor_revision="0" incr_revision="0"/>
  <CCT>5000</CCT>
  <LuxIdx>130</LuxIdx>
  <Gain>1</Gain>
  <digitalGain>1</digitalGain>
  <ExpSensitivityRatio>1</ExpSensitivityRatio>
  <ExpTimeRatio>1</ExpTimeRatio>
  <ExpGainRatio>1</ExpGainRatio>
  <DrcGain>1</DrcGain>
  <DrcGainDark>1</DrcGainDark>
  <LensPosition>0</LensPosition>
  <HDRMode>0</HDRMode>
  <gain_r>1</gain_r>
  <gain_g>1</gain_g>
  <gain_b>1</gain_b>
  <HDRZrecSel>0</HDRZrecSel>
  <HDRZrecPattern>0</HDRZrecPattern>
  <HDRZrecFirstRBExp>0</HDRZrecFirstRBExp>
  <LEDSensitivity>0</LEDSensitivity>
  <NumOfLed>1</NumOfLed>
  <Led1IdxRatio>0.1</Led1IdxRatio>
  <Led2IdxRatio>0.9</Led2IdxRatio>
  <SensorType>1</SensorType>
  <CustomAec>1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</CustomAec>
  <CustomAwb>1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</CustomAwb>
  <CustomAf>1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1</CustomAf>
  <CCM>
    <IFE>
      <Flag>0</Flag>
      <Matrix>1 0 0 0 1 0 0 0 1</Matrix>
      <Offset>0 0 0</Offset>
    </IFE>
    <BPS>
      <Flag>0</Flag>
      <Matrix>1 0 0 0 1 0 0 0 1</Matrix>
      <Offset>0 0 0</Offset>
    </BPS>
    <IPE>
      <Flag>0</Flag>
      <Matrix>1 0 0 0 1 0 0 0 1</Matrix>
      <Offset>0 0 0</Offset>
    </IPE>
  </CCM>
    <IOT>
        <exposure_ratio>29.16 32.0 32.0 32.0</exposure_ratio>
    </IOT>
</MetaConfig>

=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/Simulator/Spectra345/DefaultConfig/XML/meta_config.xml
<?xml version="1.0" encoding="utf-8" ?>
<MetaConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="..\XSD\meta_config.xsd">
    <module_version major_revision="1" minor_revision="0" incr_revision="0"/>
    <CCT>5000</CCT>
    <LuxIdx>130.0</LuxIdx>
    <Gain>1.0</Gain>
    <shortGain>1.0</shortGain>
    <digitalGain>1.0</digitalGain>
    <ExpSensitivityRatio>1.0</ExpSensitivityRatio>
    <ExpTimeRatio>1.0</ExpTimeRatio>
    <ExpGainRatio>1.0</ExpGainRatio>
    <DrcGain>1.0</DrcGain>
    <DrcGainDark>1.0</DrcGainDark>
    <LensPosition>0.0</LensPosition>
    <HDRMode>0</HDRMode>
    <gain_r>1</gain_r>
    <gain_g>1</gain_g>
    <gain_b>1</gain_b>
    <HDRZrecSel>0</HDRZrecSel>
    <HDRZrecPattern>0</HDRZrecPattern>
    <HDRZrecFirstRBExp>0</HDRZrecFirstRBExp>
    <LEDSensitivity>0.0</LEDSensitivity>
    <NumOfLed>1</NumOfLed>
    <Led1IdxRatio>0.1</Led1IdxRatio>
    <Led2IdxRatio>0.9</Led2IdxRatio>
    <SensorType>1</SensorType>
    
<!--3A Exposure time info -->
    <aec_exp_time>
        <Short>1</Short>
        <Safe>1</Safe>
        <Long>1</Long>
    </aec_exp_time>

<CustomAec>1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0</CustomAec>
    <CustomAwb>1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0</CustomAwb>
    <CustomAf>1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0</CustomAf>
    <CCM>
        <IFE>
            <Flag>0</Flag>
            <Matrix>
                1 0 0
                0 1 0
                0 0 1
            </Matrix>
            <Offset>
                0 0 0
            </Offset>
        </IFE>
        <BPS>
            <Flag>0</Flag>
            <Matrix>
                1 0 0
                0 1 0
                0 0 1
            </Matrix>
            <Offset>
                0 0 0
            </Offset>
        </BPS>
        <IPE>
            <Flag>0</Flag>
            <Matrix>
                1 0 0 
                0 1 0 
                0 0 1 
            </Matrix>
            <Offset>
                0 0 0
            </Offset>
        </IPE>
    </CCM>
</MetaConfig>
