=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/Simulator/Spectra580/DefaultConfig/XSD/spectracamsim_config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="simulationglobalelements.xsd"/>
    <xs:element name="SpectraCamSimConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="module_version">
                    <xs:complexType>
                        <xs:attribute name="major_revision" type="xs:unsignedByte" use="required" />
                        <xs:attribute name="minor_revision" type="xs:unsignedByte" use="required" />
                        <xs:attribute name="incr_revision" type="xs:unsignedByte" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="DeviceSetting">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Feature">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name">
                                            <!-- feature name, e.g BPS, IPE, MFXR, BayerToYUV, YUV2Jpeg … -->
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="BayerToYUV"/>
                                                    <xs:enumeration value="MFXR"/>
                                                    <xs:enumeration value="BPS"/>
                                                    <xs:enumeration value="IPE"/>
                                                    <xs:enumeration value="YUV2Jpeg"/>
                                                    <xs:enumeration value="HDR"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="FrameCount" type="xs:unsignedByte" />
                                        <xs:element name="SensorID" type="xs:unsignedByte" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="InputSetting">
                                <!--InputFolder: Input folder is now fixed to - data/vendor/camera -->
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="InputFolder" type="xs:string" />
                                        <xs:element name="ImageFile" type="xs:string" />
                                        <xs:element name="ISPConfig" type="xs:string" />
                                        <xs:element name="MetaConfig" type="xs:string" />
                                        <xs:element name="StreamConfig" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="OutputSetting">
                                <!--OutputFolder: Output folder is now fixed to - data/vendor/camera/output-->
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="OutputFolder" type="xs:string" />
                                        <xs:element name="OutputPrefix" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="UseCase">
                    <!-- 0: None;  1: Snapshot;  2: Video;  3: MFNR  4: QLL-->
                    <xs:simpleType>
                        <xs:restriction base="xs:unsignedByte">
                            <xs:enumeration value="0"/>
                            <xs:enumeration value="1"/>
                            <xs:enumeration value="2"/>
                            <xs:enumeration value="3"/>
                            <xs:enumeration value="4"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="TuningModeSelector">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- submode value0 for default modetype-->
                            <xs:element name="SubModeValue0" type="xs:unsignedByte" />
                            <!-- submode value1 for sensor -->
                            <xs:element name="SubModeValue1" type="xs:unsignedByte" minOccurs="0"/>
                            <xs:element name="ModeUsecaseSubModeType" type="xs:unsignedByte" minOccurs="0">
                                <!--Preview = 0, Snapshot = 1, Video = 2, ZSL = 3, Liveshot = 4-->
                            </xs:element>
                            <xs:element name="ModeFeature1SubModeType" type="xs:unsignedByte" minOccurs="0">
                                <!--None = 0, ISPHDR = 1, ADRC = 2-->
                            </xs:element>
                            <xs:element name="ModeFeature2SubModeType" type="xs:unsignedByte" minOccurs="0">
                                <!--None = 0, OISCapture = 1, HLG = 2, HDR10 = 3, MFNRBlend = 4, MFNRPostFilter = 5, MFSRBlend = 6, MFSRPostFilter = 7-->
                            </xs:element>
                            <xs:element name="ModeSceneSubModeType" type="xs:unsignedByte" minOccurs="0">
                                <!--None = 0, Landscape = 1, Snow = 2, Beach = 3, Sunset = 4, Night = 5, Portrait = 6, BackLight = 7, 
                                Sports = 8, AntiShake = 9, Flowers = 10, CandleLight = 11, Fireworks = 12, Party = 13, NightPortrait = 14,
                                Theater = 15, Action = 16, AR = 17, FacePriority = 18, Barcode = 19, BestShot = 20-->
                            </xs:element>
                            <xs:element name="ModeEffectSubModeType" type="xs:unsignedByte" minOccurs="0">
                                <!--None = 0, Mono = 1, Sepia = 2, Negative = 3, Solarize = 4, Posterize = 5, Aqua = 6, Emboss = 7, Sketch = 8,
                                Neon= 9, Blackboard = 10,Whiteboard = 11-->
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="RunPipeline">
                    <!-- 0x01: IFE;  0x02:  BPS;   0x04:  PPS;   0x08:  NPS -->
                    <!-- i.e. IFE+PPS+NPS:  0x0D;  BPS+PPS+NPS:  0x0E; -->
                    <xs:simpleType>
                        <xs:restriction base="Hex8">
                            <xs:enumeration id="IFE" value="0x1"/>
                            <xs:enumeration id="BPS" value="0x2"/>
                            <xs:enumeration id="PPS" value="0x4"/>
                            <xs:enumeration id="NPS" value="0x8"/>
                            <xs:enumeration id="IPE" value="0xc"/>
                            <xs:enumeration id="IFEIPE" value="0xd"/>
                            <xs:enumeration id="BPSIPE" value="0xe"/>
                            <xs:enumeration id="Preproc" value="0xf"/>
                            <xs:enumeration id="MFHDR" value="0x40"/>
                            <xs:enumeration id="MFHDRIPE" value="0x4c"/>
                            <xs:enumeration id="IFEMFHDRIPE" value="0x4d"/>
                            <xs:enumeration id="BPSMFHDRIPE" value="0x4e"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="MFHDRStageConfig">
                    <!-- 0x1: PreFusion;    0x2: Fusion;    0x4: PostFusion;    0xf: All -->
                    <xs:simpleType>
                        <xs:restriction base="Hex8">
                            <xs:enumeration id="PreFusion" value="0x1"/>
                            <xs:enumeration id="Fusion" value="0x2"/>
                            <xs:enumeration id="PostFusion" value="0x4"/>
                            <xs:enumeration id="All" value="0xf"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="QLLStageConfig">
                    <!-- 0x1: MLISP;    0x2: MotionAwareness;  -->
                    <xs:simpleType>
                        <xs:restriction base="Hex8">
                            <xs:enumeration id="MLISP" value="0x1"/>
                            <xs:enumeration id="MotionAwareness" value="0x2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ParamParserExeFile" type="xs:string" />
                <xs:element name="PerModule" type="xs:string" />
                <xs:element name="MFNRStageConfig">
                    <!-- 0x01: Bayer processing 0x02: Prefiltering 0x04: Blending 0x08: Postfiltering -->
                    <xs:simpleType>
                        <xs:restriction base="Hex8">
                            <xs:enumeration id="BayerProcessing" value="0x1"/>
                            <xs:enumeration id="Prefiltering" value="0x2"/>
                            <xs:enumeration id="PreFilt_Blending" value="0x6"/>
                            <xs:enumeration id="Postfiltering" value="0x8"/>
                            <xs:enumeration id="All" value="0xf"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="InputSetting">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ImageFormat">
                                <xs:simpleType>
                                    <xs:restriction base="xs:unsignedByte">
                                        <xs:enumeration value="0"/>
                                        <xs:enumeration value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ImageFile" type="xs:string" />
                            <xs:element name="TFIFile" type="xs:string" />
                            <xs:element name="InputFolder" type="xs:string" />
                            <xs:element name="ExpSequence" type="xs:string" />
                            <xs:element name="ManualLoadFile" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="EarlyExit">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Enable" type="xs:unsignedByte" />
                            <xs:element name="ModulePipeline" type="Hex8" />
                            <xs:element name="Module" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ISPConfig" type="xs:string" />
                <xs:element name="MetaConfig" type="xs:string" />
                <xs:element name="StreamConfig" type="xs:string" />
                <xs:element name="QLLCalcFrameConfig" type="xs:string" />
                <xs:element name="SchemaDir" type="xs:string" />
                <xs:element name="ChromatixHeaderXMLDir" type="xs:string" />
                <xs:element name="DataStoreFile" type="xs:string" />
                <xs:element name="SchemaValidation" type="xs:unsignedByte" />     
                <xs:element name="OutputSetting">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ImageFormat">
                                <xs:simpleType>
                                    <!-- 1: BMP;  2: YUV;  3: BMP+YUV -->
                                    <xs:restriction base="xs:unsignedByte">
                                        <xs:enumeration value="1"/>
                                        <xs:enumeration value="2"/>
                                        <xs:enumeration value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="OutputFolder" type="xs:string" />
                            <xs:element name="OutputPrefix" type="xs:string" />
                            <xs:element name="RegisterDump" type="xs:unsignedByte" />
                            <xs:element name="IntermediateSetting">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Enable" type="Hex8" />
                                        <xs:element name="statsDump" type="Hex16" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="RegisterDumpOnlyModeCfg">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="AWBMode">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Enable" type="xs:unsignedByte" />
                                                    <xs:element name="BPSCCEnable" type="xs:unsignedByte" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CustomTriggerModule" type="xs:unsignedByte" minOccurs="0" maxOccurs="1" default="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/Simulator/Spectra580/DefaultConfig/XML/spectracamsim_config.xml
<?xml version="1.0" encoding="utf-8" ?>
<SpectraCamSimConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="..\XSD\spectracamsim_config.xsd">
    <module_version major_revision="1" minor_revision="0" incr_revision="0"/>
    <DeviceSetting>
        <Feature>
            <!-- feature name, e.g BPS, IPE, MFXR, BayerToYUV, YUV2JPEG â€¦ -->
            <Name>MFXR</Name>
            <!-- number of frames for MFXR or video -->
            <FrameCount>5</FrameCount>
            <!-- Sensor ID-->
            <SensorID>0</SensorID>
        </Feature>
        <InputSetting>
            <!--InputFolder: Input folder is now fixed to - data/vendor/camera -->
            <InputFolder>/data/vendor/camera/</InputFolder>
            <ImageFile>latest.raw</ImageFile>
            <ISPConfig>/data/vendor/camera/isp_config.xml</ISPConfig>
            <MetaConfig>/data/vendor/camera/meta_config.xml</MetaConfig>
            <StreamConfig>/data/vendor/camera/stream_config.xml</StreamConfig>
        </InputSetting>
        <OutputSetting>
            <!--OutputFolder: Output folder is now fixed to - data/vendor/camera/output-->
            <OutputFolder>/data/vendor/camera/output</OutputFolder>
            <OutputPrefix>ots</OutputPrefix>
        </OutputSetting>
    </DeviceSetting>
    <!-- 0: None;  1: Snapshot;  2: Video;  3: MFNR  4: QLL -->
    <UseCase>1</UseCase>
    <TuningModeSelector>
        <SubModeValue0>0</SubModeValue0>
        <SubModeValue1>0</SubModeValue1>
        <ModeUsecaseSubModeType>0</ModeUsecaseSubModeType>
        <ModeFeature1SubModeType>0</ModeFeature1SubModeType>
        <ModeFeature2SubModeType>0</ModeFeature2SubModeType>
        <ModeSceneSubModeType>0</ModeSceneSubModeType>
        <ModeEffectSubModeType>0</ModeEffectSubModeType>
    </TuningModeSelector>
    <!-- 0x01: IFE;  0x02:  BPS;   0x04:  PPS;   0x08:  NPS -->
    <!-- i.e. IFE+PPS+NPS:  0x0D;  BPS+PPS+NPS:  0x0E; -->
    <RunPipeline>0x2</RunPipeline>
    <!-- 0x01: PreFusion;  0x02:  Fusion;   0x04:  PostFusion  -->
    <MFHDRStageConfig>0x1</MFHDRStageConfig>
    <QLLStageConfig>0x1</QLLStageConfig>
    <ParamParserExeFile>..\Simulator\Spectra480\ParameterParser.exe</ParamParserExeFile>
    <!-- None, ABF, LSC, ASF, BLS, GRA, CC, 2DLUT, GIC, LSC, BLS, WB, Demo, CC -->
    <PerModule>None</PerModule>
    <MFNRStageConfig>0xf</MFNRStageConfig>
    <InputSetting>
        <!-- 0: RAW;  1: YUV -->
        <ImageFormat>0</ImageFormat>
        <ImageFile>..\Input\MCC_D65.raw</ImageFile>
        <TFIFile></TFIFile>
        <InputFolder>..\Input\</InputFolder>
        <ExpSequence>SLM</ExpSequence>
        <ManualLoadFile></ManualLoadFile>
    </InputSetting >
    <EarlyExit>
        <Enable>0</Enable>
        <ModulePipeline>0</ModulePipeline>
        <Module>ABF</Module>
    </EarlyExit>
    <ISPConfig>..\TestData\isp_config.xml</ISPConfig>
    <MetaConfig>..\TestData\meta_config.xml</MetaConfig>
    <StreamConfig>..\TestData\stream_config.xml</StreamConfig>
    <QLLCalcFrameConfig></QLLCalcFrameConfig>
    <SchemaDir>..\Schema</SchemaDir>
    <ChromatixHeaderXMLDir>..\TestData\Chromatix</ChromatixHeaderXMLDir>
    <DataStoreFile>..\TestData\Config\dump_config.xml</DataStoreFile>
    <SchemaValidation>1</SchemaValidation>    
    <OutputSetting>
        <!-- 1: BMP;  2: YUV;  3: BMP+YUV -->
        <ImageFormat>2</ImageFormat>
        <OutputFolder>..\Simulation\Default\2018_5_23_12_34_0\</OutputFolder>
        <OutputPrefix>out_</OutputPrefix>
        <RegisterDump>1</RegisterDump>
        <IntermediateSetting>
            <Enable>1</Enable>
            <statsDump>0</statsDump>
        </IntermediateSetting>
        <RegisterDumpOnlyModeCfg>
            <AWBMode>
                <Enable>1</Enable>
                <!-- 0: disable 1: enable register dump for AWB ( IPE CC, gamma, 2DLUT only ) -->
                <BPSCCEnable>0</BPSCCEnable>
                <!-- additionally enable BPS CC -->
            </AWBMode>
        </RegisterDumpOnlyModeCfg>
    </OutputSetting>
    <CustomTriggerModule>0</CustomTriggerModule>
</SpectraCamSimConfig>
