=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/Simulator/IOT280/DefaultConfig/XSD/stream_config.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--========================================================================-->
<!-- Copyright (c) 2016-2017 Qualcomm Technologies, Inc.                    -->
<!-- All Rights Reserved.                                                   -->
<!-- Confidential and Proprietary - Qualcomm Technologies, Inc.             -->
<!--========================================================================-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="StreamConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="module_version">
                    <xs:complexType>
                        <xs:attribute name="major_revision" type="xs:int" fixed="1"/>
                        <xs:attribute name="minor_revision" type="xs:int" fixed="0"/>
                        <xs:attribute name="incr_revision" type="xs:int" fixed="0"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Width" type="xs:unsignedShort" />
                <xs:element name="Height" type="xs:unsignedShort" />
                <xs:element name="Stride" type="xs:unsignedShort" />
                <xs:element name="BayerPattern">
                    <xs:simpleType>
                        <xs:restriction base="xs:unsignedByte">
                            <xs:enumeration id="RGGB" value="0"/>
                            <xs:enumeration id="GRBG" value="1"/>
                            <xs:enumeration id="BGGR" value="2"/>
                            <xs:enumeration id="GBRG" value="3"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="BitsPerPixel" type="xs:unsignedByte" />
                <xs:element name="PackedType">
                    <xs:simpleType>
                        <xs:restriction base="xs:unsignedByte">
                            <xs:enumeration value="0"/>
                            <xs:enumeration value="1"/>
                            <xs:enumeration value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="yuvFormatType" type="xs:unsignedByte">
                    <!-- 0 : Planar , 1 : CrCb , 2: Cbcr -->
                </xs:element>
                <xs:element name="IOT">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="input_bayer_format" type="xs:unsignedByte" />
                            <xs:element name="output_bayer_format" type="xs:unsignedByte" />
                            <xs:element name="sensor_layout" type="xs:unsignedByte" />
                            <xs:element name="frame_count" type="xs:unsignedByte" />
                            <xs:element name="line_offset" type="xs:unsignedShort" />
                            <xs:element name="sensor_line_info" type="xs:unsignedByte" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Vince530/liudada/ln-p11_5j/Simulation/7.3.1.16/Simulator/IOT280/DefaultConfig/XML/stream_config.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
========================================================================
   Copyright(c) 2018 Qualcomm Technologies, Inc.
   All Rights Reserved.
   Confidential and Proprietary - Qualcomm Technologies, Inc.
========================================================================
-->
<StreamConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\XSD\stream_config.xsd">
  <module_version major_revision="1" minor_revision="0" incr_revision="0"/>
  <Width>1920</Width>
  <Height>1080</Height>
  <Stride>2592</Stride>
  <BayerPattern>1</BayerPattern>
  <BitsPerPixel>10</BitsPerPixel>
  <PackedType>0</PackedType>
  <yuvFormatType>2</yuvFormatType>
  <IOT>
	<input_bayer_format>1</input_bayer_format>
	<output_bayer_format>0</output_bayer_format>
	<sensor_layout>2</sensor_layout>
	<frame_count>2</frame_count>
	<line_offset>618</line_offset>
	<sensor_line_info>0</sensor_line_info>	
  </IOT>
</StreamConfig>
